version: "3"
services:
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
      args:
        - DOMAIN_NAME
        - CERT_KEY_PATH
        - CERT_PATH
        - CERT_SUBJECT
    env_file:
      - .env
    container_name: nginx
    volumes:
      - wp-pages:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart:
      always
    depends_on:
      - wordpress

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
      args:
        - MYSQL_HOST
        - DOMAIN_NAME
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - WP_URL
        - WP_TITLE
        - WP_ADMIN_USER
        - WP_ADMIN_PASSWORD
        - WP_ADMIN_EMAIL
        - WP_USER
        - WP_PASSWORD
        - WP_USER_EMAIL
    env_file:
      - .env
    container_name: wordpress
    volumes:
      - wp-pages:/var/www/wordpress
    networks:
      - inception
    restart:
      always
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT
        - MYSQL_ROOT_PASSWORD
    container_name: mariadb
    volumes:
      - wp-database:/var/lib/mysql
    networks:
      - inception
    restart:
      always

volumes:
  wp-database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/elraira-/data/wp-database'
  wp-pages:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/elraira-/data/wp-pages'
  
networks:
  inception:
    driver: bridge
